/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package playground.app2;

import playground.list.LinkedList;

import static playground.utilities.StringUtils.join;
import static playground.utilities.StringUtils.split;
import static playground.app2.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
