/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package playground.app2;

class MessageUtils {
    public static String getMessage() {
        return "Bye      Bitches!";
    }
}
